project:
  type: website
  output-dir: "."

website:
  title: "lab12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual

